# Generated by Django 4.2.2 on 2023-07-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
