# Generated by Django 4.2.2 on 2023-07-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
